### ISSUE TITLE
regarding non-max suppression in README

### ISSUE THREAD

**Issue by Denielll** [tejaslodaya/car-detection-yolo#1]
Hi, 

Thank you for the writeup ! It's really useful. 
I have one question regarding non-max suppression interpretation you wrote in README : 

You mentioned..

1,Select the box that has the highest score.
2,Compute its overlap with all other boxes, and remove boxes that overlap it more than iou_threshold.
3,Iterate until there's no more boxes with a lower score than the current selected box.

My question is about step3. 
What if there is a ,say, car in the up right corner of the pic with prob = 0.8, and another car in the up left corner of the pic with prob = 0.6. They are not overlapped. ( IOU = 0 )
We should keep both of them

But...if we do as what step3 says, the algorithm will remove the prob = 0.6 box right ?

**Comment by tejaslodaya** [comment]
Hi @Denielll ,
Thanks for reading my write-up. Really appreciate it.

The steps are as follows:
1. Select the box with highest score.
2. Compute its overlap with all other boxes, and remove boxes that overlap it more than iou_threshold.
3. Iterate over all the boxes which have an overlap with the selected box until there's no more boxes with a lower score than the current selected box.
(notice the rephrase in step3)

Coming to your example.
Suppose p(box1) = 0.9 and p(box2) = 0.6 but iou(box1, box2) = 0. 
The steps it follows are:
1. It will select the box1 since it has highest score
2. Since there's no overlap, box1 is selected.

Now, box2 is selected next since it is the next box with the highest score.
Follow the above steps and repeat.

Let me know if it makes sense.

**Comment by Denielll** [comment]
Wow, thanks for your prompt reply. Yeah it makes sense. Now I get it
Thank you !

**Comment by tejaslodaya** [comment]
Thanks @Denielll ,
Updated README for clarity.
